# config/packages/fos_user.yaml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "cwertyk@gmail.com"
        sender_name: "chiheb"
    registration:
                            confirmation:
                                enabled: true
