<?php

namespace App\Repository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{



        public function findPaniers($id)
     {

       $query = $this->getEntityManager()
         ->createQuery('SELECT m FROM App:Panier m WHERE m.user=:num  ');
       $query->setParameter('num', $id);

      return $query->getResult();
      }




}
